all:
	gcc server.c -o server.o
	gcc client.c -o client.o
	gcc board.c -o board.o
	gcc open.c -o open.o
	gcc signal.c -o signal.o
	gcc welcome.c -o welcome.o
client:
	./client.o
server:
	./server.o
clean:
	rm*~
