#include <stdio.h>
#include <stdlib.h>

void welcomeScreen(void){
  printf("OOOOOO\n");
  printf("OO   OO\n");
  printf("OO  OO\n");
  printf("OOOOOO\n");
  printf("OO   OO\n");
  printf("OOOOOO\n\n");
  sleep(1);
  printf(" OOOO\n\n");
  printf("OO  OO\n");
  printf("OO  OO\n");
  printf("OOOOOO\n");
  printf("OO  OO\n");
  printf("OO  OO\n");
  sleep(1);
  printf("OOOOOO\n");
  printf("  OO  \n");
  printf("  OO\n");
  printf("  OO\n");
  printf("  OO\n");
  printf("  OO\n");
  sleep(1);
  printf("OOOOOO\n");
  printf("  OO  \n");
  printf("  OO\n");
  printf("  OO\n");
  printf("  OO\n");
  printf("  OO\n");
  sleep(1);
  printf("OO\n");
  printf("OO\n");
  printf("OO\n");
  printf("OO\n");
  printf("OO\n");
  printf("OOOOOO\n");
  sleep(1);
  printf("OOOOOO\n");
  printf("OO\n");
  printf("OOOO\n");
  printf("OO\n");
  printf("OO"\n);
  printf("OOOOOO\n");
  sleep(1);
  printf();
  printf();
  printf();
  printf();
  printf();
  printf();
  sleep(1);
  printf();
  printf();
  printf();
  printf();
  printf();
  printf();
  sleep(1);
  printf();
  printf();
  printf();
  printf();
  printf();
  printf();
  sleep(1);
  printf();
  printf();
  printf();
  printf();
  printf();
  printf();
  sleep(1);