server: server.c
	gcc server.c -o server

client: client.c
	gcc client.c -o client

mary: mary.c
	gcc mary.c -o mary

suitor: suitor.c
	gcc suitor.c -o suitor

clean: 
	rm -rf *~ *# *.o mary suitor client suitor
	clear